// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezgmvrvbgaoaolxsnlhm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6Z212cnZiZ2FvYW9seHNubGhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1MDk1MjQsImV4cCI6MjA1MTA4NTUyNH0.G4mlGV8xQcQIiFzmWhXbVx0954skod7hZ6ZFUbEu0Hc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);